import type { QuickPick, Settings } from '../types'

const createdAt = '2026-01-01T00:00:00.000Z'

export const defaultSettings: Settings = {
  timerLengthMinutes: 10,
  theme: 'system',
  remindersEnabled: false,
  focusSound: 'off',
  hasCompletedOnboarding: false,
  premiumUnlocked: false,
}

export const defaultQuickPicks: QuickPick[] = [
  {
    id: 'default-tidy-room',
    title: 'Tidy room',
    icon: 'home',
    category: 'clean',
    colour: 'green',
    createdAt,
    updatedAt: createdAt,
    isDefault: true,
  },
  {
    id: 'default-study',
    title: 'Study',
    icon: 'book',
    category: 'study',
    colour: 'blue',
    createdAt,
    updatedAt: createdAt,
    isDefault: true,
  },
  {
    id: 'default-emails',
    title: 'Emails',
    icon: 'mail',
    category: 'admin',
    colour: 'purple',
    createdAt,
    updatedAt: createdAt,
    isDefault: true,
  },
  {
    id: 'default-workout',
    title: 'Workout',
    icon: 'dumbbell',
    category: 'exercise',
    colour: 'coral',
    createdAt,
    updatedAt: createdAt,
    isDefault: true,
  },
  {
    id: 'default-game-project',
    title: 'Game project',
    icon: 'gamepad',
    category: 'creative',
    colour: 'blue',
    createdAt,
    updatedAt: createdAt,
    isDefault: true,
  },
  {
    id: 'default-laundry',
    title: 'Laundry',
    icon: 'shirt',
    category: 'home',
    colour: 'green',
    createdAt,
    updatedAt: createdAt,
    isDefault: true,
  },
  {
    id: 'default-dishes',
    title: 'Dishes',
    icon: 'sparkle',
    category: 'home',
    colour: 'warning',
    createdAt,
    updatedAt: createdAt,
    isDefault: true,
  },
  {
    id: 'default-admin',
    title: 'Admin',
    icon: 'file-text',
    category: 'admin',
    colour: 'purple',
    createdAt,
    updatedAt: createdAt,
    isDefault: true,
  },
]
